using AutoDto.Generator.Models;
using Microsoft.CodeAnalysis;

namespace AutoDto.Generator;

internal class CodeGenerator {
	private readonly AutoDtoContext _autoDtoContext;
	private readonly SourceProductionContext _sourceContext;

	public CodeGenerator(SourceProductionContext sourceContext, AutoDtoContext autoDtoContext) {
		_autoDtoContext = autoDtoContext;
		_sourceContext = sourceContext;
	}

	internal static void Generate(SourceProductionContext context, AutoDtoContext _autoDtoContext) =>
		new CodeGenerator(context, _autoDtoContext).Generate();

	/// <summary>Добавление файлов</summary>
	private void Generate() {
		string targetNamespace = _autoDtoContext.Domain.ContainingNamespace.ToString();
		string domainClassName = _autoDtoContext.Domain.Name;
		string classNamespace = _autoDtoContext.Dto.ContainingNamespace.ToString();
		string className = _autoDtoContext.Dto.Name;
		string props = GetProps();

		var source = $$"""
		               // <auto-generated />

		               using {{targetNamespace}};

		               namespace {{classNamespace}};

		               /// <summary> <inheritdoc cref="{{domainClassName}}"/> </summary>
		               public partial class {{className}} {
		               {{props}}
		               }
		               """;

		_sourceContext.AddSource($"{className}.g.cs", source);
	}

	//TODO nullable
	//TODO required
	//TODO защита от доменных объектов?
	private string GetProps() {
		string domainClassName = _autoDtoContext.Domain.Name;
		var fields = _autoDtoContext.Properties.Select(field => {
			//string required = field.IsRequired ? "required " : "";

			return $$"""
			         /// <summary> <inheritdoc cref="{{domainClassName}}.{{field.Name}}"/> </summary>
			         public {{field.Type}} {{field.Name}} { get; set; }

			         """;
		});
		return string.Join("\n", fields);
	}
}